import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import type {Order, Product} from "@/shared/types";
import {formatCurrency, formatDate} from "@/helpers";

export function downloadOrderInvoice(order: Order) {
    const doc = new jsPDF();

    // Header
    doc.setFontSize(20);
    doc.setTextColor(128, 0, 255);
    doc.text("Smart Inventory", 14, 20);

    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text("INVOICE", 14, 28);

    // Order info
    doc.setFontSize(11);
    doc.setTextColor(30);
    doc.text(`Order #${order._id.slice(-6)}`, 14, 40);
    doc.setFontSize(9);
    doc.setTextColor(100);
    doc.text(`Date: ${formatDate(order.createdAt)}`, 14, 47);
    doc.text(`Customer: ${order.customerName}`, 14, 53);
    doc.text(`Status: ${order.status}`, 14, 59);

    // Items table
    const items = order.products.map((item) => {
        const name = typeof item.product === "object" ? item.product.name : "Product";
        return [name, String(item.quantity), formatCurrency(item.price), formatCurrency(item.price * item.quantity)];
    });

    autoTable(doc, {
        startY: 68,
        head: [["Product", "Qty", "Unit Price", "Subtotal"]],
        body: items,
        theme: "striped",
        headStyles: {fillColor: [128, 0, 255], fontSize: 9},
        bodyStyles: {fontSize: 9},
        columnStyles: {
            1: {halign: "center"},
            2: {halign: "right"},
            3: {halign: "right"},
        },
    });

    // Total
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const finalY = ((doc as any).lastAutoTable?.finalY as number) || 120;
    doc.setFontSize(12);
    doc.setTextColor(30);
    doc.text(`Total: ${formatCurrency(order.totalPrice)}`, 145, finalY + 12, {align: "right"});

    // Footer
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text("Generated by Smart Inventory & Order Management System", 14, 285);

    doc.save(`invoice-${order._id.slice(-6)}.pdf`);
}

export function downloadProductsReport(products: Product[]) {
    const doc = new jsPDF();

    doc.setFontSize(20);
    doc.setTextColor(128, 0, 255);
    doc.text("Smart Inventory", 14, 20);

    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text("PRODUCT INVENTORY REPORT", 14, 28);
    doc.text(`Generated: ${formatDate(new Date().toISOString())}`, 14, 34);

    const rows = products.map((p) => [
        p.name,
        typeof p.category === "object" ? p.category.name : "—",
        formatCurrency(p.price),
        String(p.quantity),
        String(p.minimumStockThreshold),
        p.status,
    ]);

    autoTable(doc, {
        startY: 42,
        head: [["Product", "Category", "Price", "Qty", "Threshold", "Status"]],
        body: rows,
        theme: "striped",
        headStyles: {fillColor: [128, 0, 255], fontSize: 8},
        bodyStyles: {fontSize: 8},
        columnStyles: {
            2: {halign: "right"},
            3: {halign: "center"},
            4: {halign: "center"},
        },
    });

    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text("Generated by Smart Inventory & Order Management System", 14, 285);

    doc.save(`inventory-report-${new Date().toISOString().split("T")[0]}.pdf`);
}
